from aicsimageio import AICSImage
import os
from glob import glob
import re
import tifffile
import numpy as np

def read_czi(path_to_file: str) -> AICSImage:
    return AICSImage(path_to_file)

def get_czi_in_folder(path_to_folder):
    path_to_folder = os.path.expanduser(path_to_folder)
    return glob(os.path.join(path_to_folder, "*.czi"))

def get_well_from_file(filename: str) -> str:
    """
    Given an input file name (auto-generated by CZI software), returns well name

    Parameters
    ----------
    filename : str
        Path to input czi file

    Returns
    ---------
    well : str
        Name of well specified in file name
    """
    pattern = r"\.czi"
    match = re.search(pattern, filename)
    idx = match.start() - 3
    return filename[idx:match.start()]

def write_tiff(data: np.ndarray, output_dir: str, file_name: str) -> None:
    output_dir = os.path.expanduser(output_dir)
    if not os.path.isdir(output_dir):
        os.mkdir(output_dir)
    full_file = os.path.join(output_dir, file_name+".tiff")
    tifffile.imwrite(full_file, data)